// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNGi_R-2AzZU8ki6izXNF1TkQ0pscKh0',
    appId: '1:398761516252:web:1c2e09ed5fae258fd12819',
    messagingSenderId: '398761516252',
    projectId: 'doorcareadmin-a9159',
    authDomain: 'doorcareadmin-a9159.firebaseapp.com',
    storageBucket: 'doorcareadmin-a9159.appspot.com',
    measurementId: 'G-ZF873KQ190',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrh7yTwAo3c-AuZgZXv1SIWt_NWL6_zto',
    appId: '1:398761516252:android:45e37e83f676a5f0d12819',
    messagingSenderId: '398761516252',
    projectId: 'doorcareadmin-a9159',
    storageBucket: 'doorcareadmin-a9159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8VKwY0Gb3RWSEYOouAxQgypBDn4rBXDc',
    appId: '1:398761516252:ios:5b25316df9b6b910d12819',
    messagingSenderId: '398761516252',
    projectId: 'doorcareadmin-a9159',
    storageBucket: 'doorcareadmin-a9159.appspot.com',
    iosBundleId: 'com.example.doorCareAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8VKwY0Gb3RWSEYOouAxQgypBDn4rBXDc',
    appId: '1:398761516252:ios:5b25316df9b6b910d12819',
    messagingSenderId: '398761516252',
    projectId: 'doorcareadmin-a9159',
    storageBucket: 'doorcareadmin-a9159.appspot.com',
    iosBundleId: 'com.example.doorCareAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnNGi_R-2AzZU8ki6izXNF1TkQ0pscKh0',
    appId: '1:398761516252:web:9731c63dec895ec8d12819',
    messagingSenderId: '398761516252',
    projectId: 'doorcareadmin-a9159',
    authDomain: 'doorcareadmin-a9159.firebaseapp.com',
    storageBucket: 'doorcareadmin-a9159.appspot.com',
    measurementId: 'G-RY2LM4K3D5',
  );
}
