// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDKeOGC0ZeMBsyQJbBsWN_SVgPxdlCqno',
    appId: '1:239875370204:web:0fe4440f22090cec7e1819',
    messagingSenderId: '239875370204',
    projectId: 'doorcareadmin-c0e68',
    authDomain: 'doorcareadmin-c0e68.firebaseapp.com',
    storageBucket: 'doorcareadmin-c0e68.appspot.com',
    measurementId: 'G-TVPX4TZ2JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL0lTsoBwX23zX_L1U2btwEpvrDEmljBg',
    appId: '1:239875370204:android:7e200efeae0e1f607e1819',
    messagingSenderId: '239875370204',
    projectId: 'doorcareadmin-c0e68',
    storageBucket: 'doorcareadmin-c0e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCbIykIvI2xIXmM_uEBZnSwAAGj_dwo4',
    appId: '1:239875370204:ios:ebd5ef665d527ff27e1819',
    messagingSenderId: '239875370204',
    projectId: 'doorcareadmin-c0e68',
    storageBucket: 'doorcareadmin-c0e68.appspot.com',
    iosBundleId: 'com.example.doorCareAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCbIykIvI2xIXmM_uEBZnSwAAGj_dwo4',
    appId: '1:239875370204:ios:ebd5ef665d527ff27e1819',
    messagingSenderId: '239875370204',
    projectId: 'doorcareadmin-c0e68',
    storageBucket: 'doorcareadmin-c0e68.appspot.com',
    iosBundleId: 'com.example.doorCareAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDKeOGC0ZeMBsyQJbBsWN_SVgPxdlCqno',
    appId: '1:239875370204:web:b2b8d6625e8cc5b77e1819',
    messagingSenderId: '239875370204',
    projectId: 'doorcareadmin-c0e68',
    authDomain: 'doorcareadmin-c0e68.firebaseapp.com',
    storageBucket: 'doorcareadmin-c0e68.appspot.com',
    measurementId: 'G-7J1VXY5HK6',
  );
}
